### ISSUE TITLE
bin/cli src - connection error but connect data is valid

### ISSUE THREAD

**Issue by Perlover** [grunch/ln-rebalance#2]
Hello!

I have strange error. I already reported about [other problem](https://github.com/grunch/ln-rebalance/issues/1)
I double checked my testnet gRPC data (i have localhost and port )

My ./.env file is

    GRPC_SSL_CIPHER_SUITES="HIGH+ECDSA"
    LNSERVICE_LND_DIR="/home/bitcoin/.lnd"
    LNSERVICE_CHAIN="bitcoin"
    LNSERVICE_NETWORK="testnet"
    LND_GRPC_PORT="10010"
    LND_HOST="localhost"

I changed localhost to 127.0.0.1 - same result
But the LND listens this host:port

    $ telnet localhost 10010
    Trying ::1...
    telnet: connect to address ::1: Connection refused
    Trying 127.0.0.1...
    Connected to localhost.
    Escape character is '^]'.
    close
    Connection closed by foreign host.

But i got always connection error as:

    $ bin/cli src
    [ 503,
      'UnexpectedGetChannelsError',
      { Error: 14 UNAVAILABLE: Connect Failed
	at Object.exports.createStatusError (/home/bitcoin/ln-rebalance/node_modules/grpc/src/common.js:87:15)
	at Object.onReceiveStatus (/home/bitcoin/ln-rebalance/node_modules/grpc/src/client_interceptors.js:1188:28)
	at InterceptingListener._callNext (/home/bitcoin/ln-rebalance/node_modules/grpc/src/client_interceptors.js:564:42)
	at InterceptingListener.onReceiveStatus (/home/bitcoin/ln-rebalance/node_modules/grpc/src/client_interceptors.js:614:8)
	at callback (/home/bitcoin/ln-rebalance/node_modules/grpc/src/client_interceptors.js:841:24)
	code: 14,
	metadata: Metadata { _internal_repr: {} },
	details: 'Connect Failed' } ]

P.S. My `admin.macaroon` file is valid and located in `/home/bitcoin/.lnd/data/chain/bitcoin/testnet/admin.macaroon`. The tls file same is valid and located `/home/bitcoin/.lnd/tls.cert`. I can make `lncli getinfo` and i got info about testnet node.

**Comment by grunch** [comment]
Hi, are you sure that your RPC port is 10010? the default port is 10009, can you paste here your ~/.lnd/lnd.conf file?

**Comment by Perlover** [comment]
Yes, i am sure
Here is my current config
I replaced private data only there:

    [Application Options]
    rpclisten=localhost:10010
    restlisten=localhost:8081
    debuglevel=info
    debughtlc=true
    autopilot.active=1
    # autopilot.maxchannels=1024
    # You need configure router for port forwarding
    externalip=MY_PUBLIC_IP:9736
    listen=MY_PUBLIC_IP:9736
    
    [Bitcoin]
    bitcoin.testnet=1
    bitcoin.active=1
    bitcoin.node=bitcoind
    
    [Bitcoind]
    bitcoind.rpcuser=lnd
    bitcoind.rpcpass=PASS_FOR_RPC
    bitcoind.zmqpubrawblock=tcp://127.0.0.1:28334
    bitcoind.zmqpubrawtx=tcp://127.0.0.1:28335

**Comment by grunch** [comment]
Your configuration apparently is ok but you have no connection with your LND daemon, which version of LND are you using?

**Comment by Perlover** [comment]
> Your configuration apparently is ok but you have no connection with your LND daemon, which version of LND are you using?

0.5.1-beta commit=v0.5.1-beta-rc3-2-g712fc3ebed1c9e0df6bad2b240acce1a0804b1d2

It's compiled master branch. I checked out to master 2-3 days ago

**Comment by Perlover** [comment]
I can checked out repo to tested by you version and recompile
I will let to know to you about results

P.S. I will test in Monday. I should go from work, sorry

**Comment by grunch** [comment]
Perfect, I'm going to test it with master

**Comment by Perlover** [comment]
Other server, same error.
I have there two LNDs instanceL: testnet & mainnet
The testnet is run at 10010 TCP port, mainnet - 10009 port
I change .env config for testnet / mainnet - same errors for both veriants

For example here is for testnet config:

    $ cat .env
    GRPC_SSL_CIPHER_SUITES="HIGH+ECDSA"
    LNSERVICE_LND_DIR="/home/bitcoin/.lnd"
    LNSERVICE_CHAIN="bitcoin"
    LNSERVICE_NETWORK="testnet"
    LND_GRPC_PORT="10010"
    LND_HOST="localhost"
    
    $ bin/cli --get_net_info
    [ 503,
      'GetNetworkInfoErr',
      { Error: 14 UNAVAILABLE: Connect Failed
	at Object.exports.createStatusError (/home/bitcoin/ln-rebalance/node_modules/ln-service/node_modules/grpc/src/common.js:87:15)
	at Object.onReceiveStatus (/home/bitcoin/ln-rebalance/node_modules/ln-service/node_modules/grpc/src/client_interceptors.js:1188:28)
	at InterceptingListener._callNext (/home/bitcoin/ln-rebalance/node_modules/ln-service/node_modules/grpc/src/client_interceptors.js:564:42)
	at InterceptingListener.onReceiveStatus (/home/bitcoin/ln-rebalance/node_modules/ln-service/node_modules/grpc/src/client_interceptors.js:614:8)
	at callback (/home/bitcoin/ln-rebalance/node_modules/ln-service/node_modules/grpc/src/client_interceptors.js:841:24)
	code: 14,
	metadata: Metadata { _internal_repr: {} },
	details: 'Connect Failed' } ]

    $ testnet-lncli getinfo
    {
	"identity_pubkey": "0315*****************************",
	"alias": "031**************",
	"num_pending_channels": 0,
	"num_active_channels": 0,
	"num_peers": 0,
	"block_height": 1445764,
	"block_hash": "000000000000009c049a9f454b678ad9147d4f0514f246ff09ab012505eeb8ac",
	"synced_to_chain": false,
	"testnet": true,
	"chains": [
	    "bitcoin"
	],
	"uris": [
	    "0315*****************@IP_HERE:9736"
	],
	"best_header_timestamp": "1430489230",
	"version": "0.5.1-beta commit=v0.5.1-beta-rc4",
	"num_inactive_channels": 51
    }

**Comment by grunch** [comment]
I don't know if this affects the connection with LND but your node is not synced
`"synced_to_chain": false`

can you check that and try again when is synced_to_chain = true?

**Comment by Perlover** [comment]
Ok, here mainnet node:

lnd.conf:

    [Application Options]
    rpclisten=localhost:10009
    restlisten=localhost:8080
    debuglevel=info
    debughtlc=false
    #autopilot.active=1
    nolisten=1
    autopilot.maxchannels=1024
    autopilot.allocation=0.9
    autopilot.maxchansize=2000000
    # You need configure router for port forwarding
    externalip=PUBLIC_IP:9735
    listen=PUBLIC_IP:9735
    alias=Test
    
    datadir=/home/bitcoin/.lnd/data/
    adminmacaroonpath=/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon
    readonlymacaroonpath=/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/readonly.macaroon
    invoicemacaroonpath=/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/invoice.macaroon
    
    [Bitcoin]
    bitcoin.mainnet=1
    bitcoin.active=1
    bitcoin.node=bitcoind
    
    [Bitcoind]
    bitcoind.rpcuser=lnd
    bitcoind.rpcpass=PASS_FOR_RPC
    bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
    bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333


getinfo from lncli:

    $ lncli getinfo
    {
	"identity_pubkey": "0243e**********************",
	"alias": "Test",
	"num_pending_channels": 0,
	"num_active_channels": 0,
	"num_peers": 3,
	"block_height": 551948,
	"block_hash": "0000000000000000001c66636e30b46cf56400c941c34c1e4c76fcc3df609d81",
	"synced_to_chain": true,
	"testnet": false,
	"chains": [
	    "bitcoin"
	],
	"uris": [
	],
	"best_header_timestamp": "1543513872",
	"version": "0.5.1-beta commit=v0.5.1-beta-rc4",
	"num_inactive_channels": 0
    }

    
`.env` file in ln-rebalance directory:

    GRPC_SSL_CIPHER_SUITES="HIGH+ECDSA"
    LNSERVICE_LND_DIR="/home/bitcoin/.lnd"
    LNSERVICE_CHAIN="bitcoin"
    LNSERVICE_NETWORK="mainnet"
    LND_GRPC_PORT="10009"
    LND_HOST="localhost"

And:

    $ bin/cli --get_net_info
    [ 503,
      'GetNetworkInfoErr',
      { Error: 14 UNAVAILABLE: Connect Failed
	at Object.exports.createStatusError (/home/bitcoin/ln-rebalance/node_modules/ln-service/node_modules/grpc/src/common.js:87:15)
	at Object.onReceiveStatus (/home/bitcoin/ln-rebalance/node_modules/ln-service/node_modules/grpc/src/client_interceptors.js:1188:28)
	at InterceptingListener._callNext (/home/bitcoin/ln-rebalance/node_modules/ln-service/node_modules/grpc/src/client_interceptors.js:564:42)
	at InterceptingListener.onReceiveStatus (/home/bitcoin/ln-rebalance/node_modules/ln-service/node_modules/grpc/src/client_interceptors.js:614:8)
	at callback (/home/bitcoin/ln-rebalance/node_modules/ln-service/node_modules/grpc/src/client_interceptors.js:841:24)
	code: 14,
	metadata: Metadata { _internal_repr: {} },
	details: 'Connect Failed' } ]

**Comment by Perlover** [comment]
And i have there (last mainnet example) installed `lncli-web` (https://github.com/mably/lncli-web)
And i checked now - there are all info is loaded in browser.
The `lncli-web` written in Node.JS too and it uses gRPC too.
So i don't think that my problem in Node.JS for example

P.S. And i have tls.cert made by this rules:

https://github.com/mably/lncli-web#generate-lnd-certificates-compatible-with-nodejs-grpc

**Comment by Perlover** [comment]
I resolved my problem!

I generated certificate method described in `lncli-web` utility: https://github.com/mably/lncli-web#generate-lnd-certificates-compatible-with-nodejs-grpc

Now i deleted `tls.cert` & `tls.key` and additional added the option `tlsextraip=127.0.0.1` (i googled about it but i am not sure that this option helped to me - i will test without it)
And after i tun `lnd` - it created new tls.cert and command works!
Sorry!

**Comment by grunch** [comment]
great I'm happy you solve it, I'm adding new functionalities to the code, in few weeks we'll have a web UI for do the same that we can do by CLI, a lot more user friendly, thank you for test it

**Comment by Perlover** [comment]
I commented the `tlsextraip` option in `lnd.conf`, deleted certificate and recreated by lnd again
After i decoded the cretificate - there are already 127.0.0.1, localhost and other IPs of server
I tested bin/cli again - it works. So main reason was bad certificate created by `lncli-web` hints ;)

**Comment by Perlover** [comment]
The rebalance in testnet works fine!
Only there is many manual work :)
Do you plan to do something auto-pilot mode? :)
For example same command for auto-pilot:

`bin/cli --max-fee-percent=0.01  --max-all-fees=10000`

(maximum 0.01% from payment sum of each payment for rebalacing and not more 10000 satoshies for all fees)

**Comment by grunch** [comment]
yes, there's a lot of work to do, but when you say manual work, what exactly do you mean?

atm with only one command you can rebalance the destination channel that you indicate to the cli

**Comment by Perlover** [comment]
I mean that i should calculate the amount which i should send,  the id of channel (dst). If my node will have 100 channels i should make many manual work

**Comment by grunch** [comment]
the system does that already, I just disabled it to make a simple visual example when I did the explanation video, I'll be enabling that soon, but is in the code, you can check it if you want
